num_workers: 15
batch_size: 1024
epochs: 4
lr: 0.01
weight_decay: 0.00001
momentum: 0.9
lr_scheduler: cyclic
step_size: 10
lr_milestones: 20,25
lr_peak_epoch: 5
gamma: 0.1
eval_epochs: 100
train_decoder_type: center_crop_256
train_path: /mnt/xfs/datasets/transfer_datasets/chestxray14/chestxray14_train.beton
val_path: /mnt/xfs/datasets/transfer_datasets/chestxray14/chestxray14_test.beton
test_path: /mnt/xfs/datasets/transfer_datasets/chestxray14/chestxray14_test.beton
train_ds_size: 49152
test_ds_size: 22433
num_classes: 10
multiclass: 7
