num_workers: 15
batch_size: 512
epochs: 10
lr: 0.1
weight_decay: 0.0005
momentum: 0.9
lr_scheduler: cyclic
step_size: 10
lr_milestones: 20,25
lr_peak_epoch: 5
gamma: 0.1
eval_epochs: 100
train_decoder_type: center_crop_256
train_path: /mnt/xfs/datasets/transfer_datasets/cifar10/cifar10_train.beton
val_path: /mnt/xfs/datasets/transfer_datasets/cifar10/cifar10_test.beton
test_path: /mnt/xfs/datasets/transfer_datasets/cifar10/cifar10_test.beton
train_ds_size: 50000
test_ds_size: 10000
num_classes: 10
multiclass: -1