num_workers: 15
batch_size: 1024
epochs: 16
lr: 0.5
weight_decay: 0.00005
momentum: 0.9
lr_scheduler: cyclic
step_size: 30
lr_milestones: 20,25
lr_peak_epoch: 2
gamma: 0.1
eval_epochs: 100
train_decoder_type: random_resized_crop
train_path: /mnt/xfs/datasets/transfer_datasets/torch_imagenet/imagenet_train.beton
val_path: /mnt/xfs/datasets/transfer_datasets/torch_imagenet/imagenet_train.beton
test_path: /mnt/xfs/datasets/transfer_datasets/torch_imagenet/imagenet_val.beton
train_inds_path: /mnt/xfs/projects/trak_transfer_fairness_imagenet_data/splits/imagenet_train_inds.npy
val_inds_path: /mnt/xfs/projects/trak_transfer_fairness_imagenet_data/splits/imagenet_val_inds.npy
train_ds_size: 1153050
val_ds_size: 128117
test_ds_size: 50000
num_classes: 1000